# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test_ui\input_account_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(387, 231)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.api_key_label = QtWidgets.QLabel(Dialog)
        self.api_key_label.setObjectName("api_key_label")
        self.gridLayout.addWidget(self.api_key_label, 0, 0, 1, 1)
        self.save_pushButton = QtWidgets.QPushButton(Dialog)
        self.save_pushButton.setObjectName("save_pushButton")
        self.gridLayout.addWidget(self.save_pushButton, 1, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.api_key_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.api_key_lineEdit.setObjectName("api_key_lineEdit")
        self.horizontalLayout.addWidget(self.api_key_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.api_key_label.setText(_translate("Dialog", "Api Key"))
        self.save_pushButton.setText(_translate("Dialog", "Save"))
