# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test_ui\base_table_for_stat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_for_stat(object):
    def setupUi(self, table_for_stat):
        table_for_stat.setObjectName("table_for_stat")
        table_for_stat.resize(513, 327)
        self.gridLayout = QtWidgets.QGridLayout(table_for_stat)
        self.gridLayout.setObjectName("gridLayout")
        self.link_pushButton = QtWidgets.QPushButton(table_for_stat)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.link_pushButton.sizePolicy().hasHeightForWidth())
        self.link_pushButton.setSizePolicy(sizePolicy)
        self.link_pushButton.setObjectName("link_pushButton")
        self.gridLayout.addWidget(self.link_pushButton, 0, 1, 1, 1)
        self.title_label = QtWidgets.QLabel(table_for_stat)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(table_for_stat)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 2)

        self.retranslateUi(table_for_stat)
        QtCore.QMetaObject.connectSlotsByName(table_for_stat)

    def retranslateUi(self, table_for_stat):
        _translate = QtCore.QCoreApplication.translate
        table_for_stat.setWindowTitle(_translate("table_for_stat", "base_table"))
        self.link_pushButton.setText(_translate("table_for_stat", "PushButton"))
        self.title_label.setText(_translate("table_for_stat", "TextLabel"))
