# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test_ui\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(730, 242)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.save_settings_pushButton = QtWidgets.QPushButton(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_settings_pushButton.sizePolicy().hasHeightForWidth())
        self.save_settings_pushButton.setSizePolicy(sizePolicy)
        self.save_settings_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.save_settings_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.save_settings_pushButton.setObjectName("save_settings_pushButton")
        self.gridLayout.addWidget(self.save_settings_pushButton, 5, 0, 1, 3, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.apis_comboBox = QtWidgets.QComboBox(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apis_comboBox.sizePolicy().hasHeightForWidth())
        self.apis_comboBox.setSizePolicy(sizePolicy)
        self.apis_comboBox.setObjectName("apis_comboBox")
        self.gridLayout.addWidget(self.apis_comboBox, 0, 2, 1, 1)
        self.apis_label = QtWidgets.QLabel(Settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.apis_label.setFont(font)
        self.apis_label.setObjectName("apis_label")
        self.gridLayout.addWidget(self.apis_label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.protection_symbol_horizontalLayout = QtWidgets.QHBoxLayout()
        self.protection_symbol_horizontalLayout.setObjectName("protection_symbol_horizontalLayout")
        self.protection_symbol_label = QtWidgets.QLabel(Settings)
        self.protection_symbol_label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.protection_symbol_label.setFont(font)
        self.protection_symbol_label.setObjectName("protection_symbol_label")
        self.protection_symbol_horizontalLayout.addWidget(self.protection_symbol_label)
        self.horizontalLayout.addLayout(self.protection_symbol_horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.protection_symbol_lineEdit = QtWidgets.QLineEdit(Settings)
        self.protection_symbol_lineEdit.setObjectName("protection_symbol_lineEdit")
        self.horizontalLayout.addWidget(self.protection_symbol_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 3, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.save_settings_pushButton.setText(_translate("Settings", "Сохранить"))
        self.apis_label.setText(_translate("Settings", "Сервис перевода"))
        self.protection_symbol_label.setText(_translate("Settings", "Символ для протекции"))
