# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\test_ui\stat_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatTable(object):
    def setupUi(self, StatTable):
        StatTable.setObjectName("StatTable")
        StatTable.resize(883, 834)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StatTable.sizePolicy().hasHeightForWidth())
        StatTable.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(StatTable)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(StatTable)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 863, 783))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.save_csv_pushButton = QtWidgets.QPushButton(StatTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_csv_pushButton.sizePolicy().hasHeightForWidth())
        self.save_csv_pushButton.setSizePolicy(sizePolicy)
        self.save_csv_pushButton.setObjectName("save_csv_pushButton")
        self.horizontalLayout.addWidget(self.save_csv_pushButton)
        self.open_statements_pushButton = QtWidgets.QPushButton(StatTable)
        self.open_statements_pushButton.setObjectName("open_statements_pushButton")
        self.horizontalLayout.addWidget(self.open_statements_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(StatTable)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout.addWidget(self.close_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(StatTable)
        QtCore.QMetaObject.connectSlotsByName(StatTable)

    def retranslateUi(self, StatTable):
        _translate = QtCore.QCoreApplication.translate
        StatTable.setWindowTitle(_translate("StatTable", "Статистика"))
        self.save_csv_pushButton.setText(_translate("StatTable", "Сохранить CSV файл"))
        self.open_statements_pushButton.setText(_translate("StatTable", "Открыть папку с отчетами"))
        self.close_pushButton.setText(_translate("StatTable", "Закрыть"))
